### ISSUE TITLE
Client/Server architecture for easier management

### ISSUE THREAD

**Issue by grdmoney** [sgoulas/pdpProject#8]
I must commend your effort @sgoulas for building a fullstack app using one of the best stacks. One thing that remains is properly separating your directories. 

One suggestion is to create a directory called `client` alongside the `server` directory you already have. Or you can divide them entirely into different repos so they can have separate deployment.

This way, it would be easier to deploy them individually without fail.

**Comment by sgoulas** [comment]
Thank you kindly. You are correct, as I was building the app I realised that it was essentially a mono-repo where the back end and front end live together but have to be deployed separately. This introduces some concerns like dependency management, multiple manifest files, separate CI/CD pipelines and as you pointed out separate deployments.

This was something I did not foresee when choosing to mock the back end in the same repository, so definitely a learning point for me. In the future I might separate the code in two repos or read about mono-repos (I think big tech companies prefer them over multiple smaller repositories so it might be a good case study for me).
